tip:
  port: 6051
  server: ssc.wlan.local
  username: support@example.com
  password: support

certificates:
  keyfile: keyfile.pem
  certfile: certfile.pem
  password: mypassword

ucentral:
  port: 1991
  listeners: 100

logger:
  size: 10
  days: 31

ui:
  port: 9771
  username: support@example.com
  password: support



