---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kuberentes.io/name: {{ include "ucentralgw.name" . }}
    helm.sh/chart: {{ include "ucentralgw.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "ucentralgw.fullname" . }}-config
data:
  ucentral.properties: |
{{ .Values.config | indent 4 }}
