---
apiVersion: v1
metadata:
  labels:
    app.kuberentes.io/name: {{ include "owgw.name" . }}
    helm.sh/chart: {{ include "owgw.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: {{ include "owgw.fullname" . }}-config
kind: Secret
type: Opaque
data:
  owgw.properties: {{ include "owgw.config" . | b64enc }}
