openapi: 3.0.3
info:
  title: CloudSDK Manufacturer API
  description: APIs that provide services for viewing, updating and deleting various data elements of manufacturers.
  version: 1.0.0
servers:
  - url: https://localhost:9091
    description: Local Dev server
  - url: https://10.0.0.61:9091
    description: Local Dev server - all-in-one
  - url: https://192.168.0.143:9051
    description: Local Dev server - portal, prov, and ssc
    
tags:
- name: Data Model Overview
- name: Manufacturer Data
    
components:
  securitySchemes:
    tip_wlan_ts_auth:
      type: http
      scheme: bearer
      
  responses:
    GenericApiError:
      description: this object is returned in the cases when an API throws an exception
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/JsonSerializedException'
            
  schemas:
    
#
#Generic data models used for many APIs
#
    GenericResponse:
      properties:
        message:
          type: string
        success:
          type: boolean
          
    JsonSerializedException:
      description: this object is returned in the cases when an API throws an exception
      properties:
        exType:
          type: string
          enum:
            - IllegalStateException
        error:
          description: error message
          type: string
        path:
          description: API path with parameters that produced the exception
          type: string
        timestamp:
          description: time stamp of when the exception was generated
          type: integer
          format: int64
          
#
# Manufacturer objects
#
    ManufacturerDetailsRecord:
      properties:
        id:
          type: integer
          format: int64
        manufacturerName:
          type: string
        manufacturerAlias:
          type: string
        createdTimestamp:
          type: integer
          format: int64
        lastModifiedTimestamp:
          description: must be provided for update operation, update will be rejected if provided value does not match the one currently stored in the database
          type: integer
          format: int64

    ManufacturerOuiDetails:
      properties:
        oui:
          description: first 3 bytes of MAC address, expressed as a string like '1a2b3c'
          type: string
        manufacturerName:
          type: string
        manufacturerAlias:
          type: string

    ManufacturerOuiDetailsPerOuiMap:
      additionalProperties:
        $ref: '#/components/schemas/ManufacturerOuiDetails'


## ---------------------------------------------------------------------------
security:
 - tip_wlan_ts_auth: []
paths:
 
  /api/manufacturer/oui:
    post:
      tags:
      - Manufacturer Data
      summary: Creates oui details
      operationId: createOuiDetails
      requestBody:
        description: Manufacturer Oui Details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManufacturerOuiDetails'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManufacturerOuiDetails'
        500: 
          $ref: '#/components/responses/GenericApiError'
    get:
      tags:
      - Manufacturer Data
      summary: Get manufacturer OUI details by OUI
      operationId: getByOui
      parameters:
      - name: oui
        in: query
        description: OUI
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManufacturerOuiDetails'
        500: 
          $ref: '#/components/responses/GenericApiError'
    delete:
      tags:
      - Manufacturer Data
      summary: Deletes manufacturer OUI details by OUI
      operationId: deleteOuiDetails
      parameters:
      - name: oui
        in: query
        description: OUI
        required: true
        schema:
          type: string
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManufacturerOuiDetails'
        500: 
          $ref: '#/components/responses/GenericApiError'
          
  /api/manufacturer/oui/forManufacturer:
    get:
      tags:
      - Manufacturer Data
      summary: Get OUI List for Manufacturers
      operationId: getOuiListForManufacturers
      parameters:
      - name: manufacturer
        in: query
        description: Manufacturer
        required: true
        schema:
          type: string
      - name: exactMatch
        in: query
        description: Exact match?
        required: true
        schema:
          type: boolean
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        500:
          $ref: '#/components/responses/GenericApiError'
  
  /api/manufacturer:
    post:
      tags:
      - Manufacturer Data
      summary: Creates manufacturer details
      operationId: createManufacturerDetails
      requestBody:
        description: Manufacturer Details Record
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManufacturerDetailsRecord'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManufacturerDetailsRecord'
        500: 
          $ref: '#/components/responses/GenericApiError'
    get:
      tags:
      - Manufacturer Data
      summary: Get manufacturer details record by ID
      operationId: getByID
      parameters:
      - name: id
        in: query
        description: ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManufacturerDetailsRecord'
        500: 
          $ref: '#/components/responses/GenericApiError'
    put:
      tags:
      - Manufacturer Data
      summary: update manufacturer details
      operationId: updateManufacturerDetails
      requestBody:
        description: Manufacturer Details Record
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManufacturerDetailsRecord'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManufacturerDetailsRecord'
        500: 
          $ref: '#/components/responses/GenericApiError'
    delete:
      tags:
      - Manufacturer Data
      summary: Deletes manufacturer detail record by ID
      operationId: deleteManufacturerDetails
      parameters:
      - name: id
        in: query
        description: ID
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManufacturerDetailsRecord'
        500: 
          $ref: '#/components/responses/GenericApiError'
  
  /api/manufacturer/oui/all:
    get:
      tags:
      - Manufacturer Data
      summary: Get List of Manufacturer OUI Details
      operationId: getAllManufacturerData
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ManufacturerOuiDetails'
        500:
          $ref: '#/components/responses/GenericApiError'
          
  /api/manufacturer/oui/upload:
    post:
      tags:
       - Manufacturer Data
      summary: Upload the gziped OUI DataFile, in the format that is published by IEEE. Latest sanitized IEEE OUI data file (oui.txt.gz) can be obtained from https://linuxnet.ca/ieee/oui/
      operationId: uploadOuiDataFile
      parameters:
      - name: fileName
        in: query
        description: file name that is being uploaded
        required: true
        schema:
          type: string
      requestBody:
        description: Contents of gziped OUI DataFile, raw
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary         
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GenericResponse'
        500:
          $ref: '#/components/responses/GenericApiError'
          
  /api/manufacturer/oui/list:
    get:
      tags:
      - Manufacturer Data
      summary: Get Manufacturer Details for OUI list
      operationId: getManufacturerDetailsForOuiList
      parameters:
      - name: ouiList
        in: query
        required: true
        content:
          text/plain:
            schema:
              type: array
              items:
                type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManufacturerOuiDetailsPerOuiMap'
        500:
          $ref: '#/components/responses/GenericApiError'

  /api/manufacturer/oui/alias:
    put:
      tags:
       - Manufacturer Data
      summary: Update alias for ManufacturerOuiDetails
      operationId: updateOuiAlias
      requestBody:
        description: ManufacturerOuiDetails info
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManufacturerOuiDetails'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ManufacturerOuiDetails'
        500:
          $ref: '#/components/responses/GenericApiError'
    get:
      tags:
       - Manufacturer Data
      summary: Get manufacturer aliases that begin with the given prefix
      operationId: getAliasValuesThatBeginWith
      parameters:
      - name: prefix
        in: query
        description: prefix for the manufacturer alias
        required: true
        schema:
          type: string
      - name: maxResults
        in: query
        description: max results to return, use -1 for no limit
        required: true
        schema:
          type: integer
          format: int32
          default: -1
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        500:
          $ref: '#/components/responses/GenericApiError'
