openapi: 3.0.3
info:
  title: CloudSDK Service Adoption Metrics API
  description: APIs that provide services for viewing, and updating service adoption metrics.
  version: 1.0.0
servers:
  - url: https://localhost:9091
    description: Local Dev server
  - url: https://10.0.0.61:9091
    description: Local Dev server - all-in-one
  - url: https://192.168.0.143:9051
    description: Local Dev server - portal, prov, and ssc
  - url: https://localhost:9092
    description: Local prov server
    
tags:
- name: Data Model Overview
- name: Service Adoption Metrics
    
components:
  securitySchemes:
    tip_wlan_ts_auth:
      type: http
      scheme: basic
      
  responses:
    GenericApiError:
      description: this object is returned in the cases when an API throws an exception
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/JsonSerializedException'
            
  schemas:
    
#
#Generic data models used for many APIs
#
    GenericResponse:
      properties:
        message:
          type: string
        success:
          type: boolean
          
    JsonSerializedException:
      description: this object is returned in the cases when an API throws an exception
      properties:
        exType:
          type: string
          enum:
            - IllegalStateException
        error:
          description: error message
          type: string
        path:
          description: API path with parameters that produced the exception
          type: string
        timestamp:
          description: time stamp of when the exception was generated
          type: integer
          format: int64
          
#
# Objects related to service adoption metrics
#
    ServiceAdoptionMetrics:
      properties:
        year:
          type: integer
          format: int32
        month:
          type: integer
          format: int32
        weekOfYear:
          type: integer
          format: int32
        dayOfYear:
          type: integer
          format: int32
        customerId:
          type: integer
          format: int32
        locationId:
          type: integer
          format: int64
        equipmentId:
          type: integer
          format: int64
        numUniqueConnectedMacs:
          description: number of unique connected MAC addresses for the data point. Note - this number is accurate only at the lowest level of granularity - per AP per day. In case of aggregations - per location/customer or per week/month - this number is just a sum of corresponding datapoints, and it does not account for non-unique MACs in those cases.
          type: integer
          format: int64
        numBytesUpstream:
          type: integer
          format: int64
        numBytesDownstream:
          type: integer
          format: int64


## ---------------------------------------------------------------------------
security:
 - tip_wlan_ts_auth: []
paths:
 
          
  /api/adoptionMetrics/perEquipmentPerDay:
    get:
      tags:
      - Service Adoption Metrics
      summary: Get daily service adoption metrics for a given year filtered by specified equipment ids
      operationId: getAdoptionMetricsPerEquipmentPerDay
      parameters:
      - name: year
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: equipmentIds
        in: query
        description: filter by equipment ids.
        required: true
        content:
          text/plain:
            schema:
              type: array
              items:
                type: integer
                format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceAdoptionMetrics'
        500:
          $ref: '#/components/responses/GenericApiError'
          
  /api/adoptionMetrics/perLocationPerDay:
    get:
      tags:
      - Service Adoption Metrics
      summary: Get daily service adoption metrics for a given year aggregated by location and filtered by specified location ids
      operationId: getAdoptionMetricsPerLocationPerDay
      parameters:
      - name: year
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: locationIds
        in: query
        description: filter by location ids.
        required: true
        content:
          text/plain:
            schema:
              type: array
              items:
                type: integer
                format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceAdoptionMetrics'
        500:
          $ref: '#/components/responses/GenericApiError'    
          
  /api/adoptionMetrics/perCustomerPerDay:
    get:
      tags:
      - Service Adoption Metrics
      summary: Get daily service adoption metrics for a given year aggregated by customer and filtered by specified customer ids
      operationId: getAdoptionMetricsPerCustomerPerDay
      parameters:
      - name: year
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: customerIds
        in: query
        description: filter by customer ids.
        required: true
        content:
          text/plain:
            schema:
              type: array
              items:
                type: integer
                format: int32
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceAdoptionMetrics'
        500:
          $ref: '#/components/responses/GenericApiError'    
          
  /api/adoptionMetrics/allPerMonth:
    get:
      tags:
      - Service Adoption Metrics
      summary: Get monthly service adoption metrics for a given year
      operationId: getAdoptionMetricsAllPerMonth
      parameters:
      - name: year
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceAdoptionMetrics'
        500:
          $ref: '#/components/responses/GenericApiError'
        
  /api/adoptionMetrics/allPerWeek:
    get:
      tags:
      - Service Adoption Metrics
      summary: Get weekly service adoption metrics for a given year
      operationId: getAdoptionMetricsAllPerWeek
      parameters:
      - name: year
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceAdoptionMetrics'
        500:
          $ref: '#/components/responses/GenericApiError'          
          
  /api/adoptionMetrics/allPerDay:
    get:
      tags:
      - Service Adoption Metrics
      summary: Get daily service adoption metrics for a given year
      operationId: getAdoptionMetricsAllPerDay
      parameters:
      - name: year
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceAdoptionMetrics'
        500:
          $ref: '#/components/responses/GenericApiError'          
          
  /api/adoptionMetrics:
    post:
      tags:
      - Service Adoption Metrics
      summary: Update a batch of service adoption metrics
      operationId: updateAdoptionMetricsBatch
      requestBody:
        description: metrics to update
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/ServiceAdoptionMetrics'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GenericResponse'
        500:
          $ref: '#/components/responses/GenericApiError'          

  /api/adoptionMetrics/uniqueMacs:
    post:
      tags:
      - Service Adoption Metrics
      summary: update stored unique macs for a given day
      operationId: updateUniqueMacs
      parameters:
      - name: timestampMs
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: customerId
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: locationId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: equipmentId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: clientMacSet
        in: query
        required: true
        content:
          text/plain:
            schema:
              type: array
              items:
                type: integer
                format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GenericResponse'
        500:
          $ref: '#/components/responses/GenericApiError'
    delete:
      tags:
      - Service Adoption Metrics
      summary: delete stored unique macs older than a given timestamp
      operationId: deleteUniqueMacs
      parameters:
      - name: createdBeforeTimestampMs
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: customerId
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: locationId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: equipmentId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GenericResponse'
        500:
          $ref: '#/components/responses/GenericApiError'
          
  /api/adoptionMetrics/uniqueMacsCount:
    get:
      tags:
      - Service Adoption Metrics
      summary: get count of unique macs for a given day
      operationId: getUniqueMacsCount
      parameters:
      - name: year
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: dayOfYear
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: customerId
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: locationId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      - name: equipmentId
        in: query
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: integer
                format: int64
        500:
          $ref: '#/components/responses/GenericApiError'

  /api/adoptionMetrics/uniqueMacs/finalize:
    post:
      tags:
      - Service Adoption Metrics
      summary: finalize stored unique macs counts for a given day and clean up individual mac records
      operationId: finalizeUniqueMacs
      parameters:
      - name: year
        in: query
        required: true
        schema:
          type: integer
          format: int32
      - name: dayOfYear
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GenericResponse'
        500:
          $ref: '#/components/responses/GenericApiError'