apiVersion: v2
appVersion: "1.0"
description: A Helm chart for Kubernetes
name: owgw
version: 0.1.0
dependencies:
- name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 10.9.2
  condition: postgresql.enabled
- name: mysql
  repository: https://charts.bitnami.com/bitnami
  version: 8.8.3
  condition: mysql.enabled
- name: mariadb
  repository: https://charts.bitnami.com/bitnami
  version: 9.4.2
  condition: mariadb.enabled
