apiVersion: v2
appVersion: "3.0.5"
description: A Helm chart for Kubernetes
name: owgw
version: 0.1.0
dependencies:
  - name: postgresql
    repository: https://tip.jfrog.io/artifactory/tip-wlan-cloud-ucentral-helm/
    version: 10.9.2
    condition: postgresql.enabled
  - name: mysql
    repository: https://tip.jfrog.io/artifactory/tip-wlan-cloud-ucentral-helm/
    version: 8.8.3
    condition: mysql.enabled
  - name: mariadb
    repository: https://tip.jfrog.io/artifactory/tip-wlan-cloud-ucentral-helm/
    version: 9.4.2
    condition: mariadb.enabled
