name: CI

on:
  push:
    paths-ignore:
      - 'openapi/**'
      - '**.md'
    branches:
      - master
      - 'release/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-20.04
    env:
      DOCKER_REGISTRY_URL: tip-tip-wlan-cloud-ucentral.jfrog.io
      DOCKER_REGISTRY_USERNAME: ucentral
    steps:
    - name: Checkout actions repo
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/.github
        path: github
        ref: WIFI-6729-speed-up-image-build

    - name: Build and push Docker image
      uses: ./github/composite-actions/docker-image-build
      with:
        image_name: owgw
        registry: tip-tip-wlan-cloud-ucentral.jfrog.io
        registry_user: ucentral
        registry_password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Checkout actions repo
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/.github
        path: github
        ref: WIFI-6729-speed-up-image-build

  trigger-testing:
    if: startsWith(github.ref, 'refs/pull/')
    runs-on: ubuntu-latest
    needs: docker
    steps:
    - name: Get base branch name and set as output
      id: get_base_branch
      run: |
        echo ::set-output name=branch::$(echo ${GITHUB_BASE_REF##*/} | sed 's/master/main/g')

    - name: Checkout actions repo
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/.github
        path: github
        ref: WIFI-6729-speed-up-image-build

    - name: Trigger testing of OpenWifi Docker Compose deployment and wait for result
      uses: ./github/composite-actions/trigger-workflow-and-wait
      env:
        BASE_BRANCH: ${{ steps.get_base_branch.outputs.branch }}
      with:
        owner: Telecominfraproject
        repo: wlan-testing
        workflow: ow_docker-compose.yml
        token: ${{ secrets.WLAN_TESTING_PAT }}
        ref: master
        inputs: '{"owgw_version": "${{ github.sha }}", "owgwui_version": "${{ env.BASE_BRANCH }}", "owsec_version": "${{ env.BASE_BRANCH }}", "owfms_version": "${{ env.BASE_BRANCH }}", "owprov_version": "main", "owprovui_version": "main"}'
