name: CI

on:
  push:
    paths-ignore:
      - 'openapi/**'
      - '**.md'
    branches:
      - master
      - 'release/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-20.04
    env:
      DOCKER_REGISTRY_URL: tip-tip-wlan-cloud-ucentral.jfrog.io
      DOCKER_REGISTRY_USERNAME: ucentral
    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t wlan-cloud-owgw:${{ github.sha }} .

    - name: Tag Docker image
      run: |
        TAGS="${{ github.sha }}"

        if [[ ${GITHUB_REF} == "refs/heads/"* ]]
        then
          CURRENT_TAG=$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
          TAGS="$TAGS $CURRENT_TAG"
        else
          if [[ ${GITHUB_REF} == "refs/tags/"* ]]
          then
            CURRENT_TAG=$(echo ${GITHUB_REF#refs/tags/} | tr '/' '-')
            TAGS="$TAGS $CURRENT_TAG"
          else # PR build
            CURRENT_TAG=$(echo ${GITHUB_HEAD_REF#refs/heads/} | tr '/' '-')
            TAGS="$TAGS $CURRENT_TAG"
          fi
        fi

        echo "Result tags: $TAGS"

        for tag in $TAGS; do
          docker tag wlan-cloud-owgw:${{ github.sha }} ${{ env.DOCKER_REGISTRY_URL }}/owgw:$tag
        done

    - name: Log into Docker registry
      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/pull/') || github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY_URL }}
        username: ${{ env.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Push Docker images
      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/pull/') || github.ref == 'refs/heads/master'
      run: |
        docker images | grep ${{ env.DOCKER_REGISTRY_URL }}/owgw | awk -F ' ' '{print $1":"$2}' | xargs -I {} docker push {}

  docker-compose:
    if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/pull/') || github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    needs: docker
    steps:
    - name: Check out wlan-cloud-ucentral-deploy repository
      uses: actions/checkout@v2
      with:
        repository: Telecominfraproject/wlan-cloud-ucentral-deploy
        path: wlan-cloud-ucentral-deploy

    - name: Instantiate Docker Compose deployment
      working-directory: ./wlan-cloud-ucentral-deploy/docker-compose
      env:
        OWGW_TAG: ${{ github.sha }}
      run: |
        docker-compose up -d

    - name: Wait for OWSec to be alive and kicking
      run: |
        n=0
        until [ "$n" -ge 3 ]
        do
          curl -s 127.0.0.1:16102 && break
          n=$((n+1))
          if [ "$n" -eq 3]; then
            exit 1
          else
            sleep 3
          fi
        done

    - name: Check out wlan-cloud-ucentralgw repository
      uses: actions/checkout@v2
      with:
        path: wlan-cloud-ucentralgw

    - name: Check functionality of microservices
      env:
        OWSEC: "openwifi.wlan.local:16001"
        FLAGS: "-s --cacert ./wlan-cloud-ucentral-deploy/docker-compose/certs/restapi-ca.pem --resolve openwifi.wlan.local:16001:127.0.0.1"
      run: |
        ./wlan-cloud-ucentralgw/test_scripts/curl/cli listdevices

    - name: Display information about running containers and log ucentralgw output
      working-directory: ./wlan-cloud-ucentral-deploy/docker-compose
      if: always()
      run: |
        docker-compose ps -a
        docker-compose logs

    # disable until repo is public
    #- name: export Docker image
    #  run: docker image save -o wlan-cloud-ucentralgw-${{ github.sha }}.tar wlan-cloud-ucentralgw:${{ github.sha }}

    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: docker-image
    #    path: wlan-cloud-ucentralgw-${{ github.sha }}.tar
