name: CI

on:
  push:
    paths-ignore:
      - 'openapi/**'
      - '**.md'
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-20.04
    env:
      DOCKER_REGISTRY_URL: tip-tip-wlan-cloud-ucentral.jfrog.io
      DOCKER_REGISTRY_USERNAME: ucentral
    steps:
    - uses: actions/checkout@v2

    - name: build Docker image
      run: docker build -t wlan-cloud-ucentralgw:${{ github.sha }} .

    - name: log into Docker registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY_URL }}
        username: ${{ env.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: push Docker image
      run: |
        TAGS="${{ github.sha }}"

        if [ ${GITHUB_REF} == "refs/heads/master" ]
        then
          TAGS="$TAGS ${GITHUB_REF#refs/heads/}"
        else # PR build
          CURRENT_TAG=$(echo ${GITHUB_HEAD_REF#refs/heads/} | tr '/' '-')
          TAGS="$TAGS $CURRENT_TAG"
        fi

        echo "Pushing tags $TAGS"

        for tag in $TAGS; do
          docker tag wlan-cloud-ucentralgw:${{ github.sha }} ${{ env.DOCKER_REGISTRY_URL }}/ucentralgw:$tag
          docker push ${{ env.DOCKER_REGISTRY_URL }}/ucentralgw:$tag
        done

  docker-compose:
    runs-on: ubuntu-20.04
    needs: docker
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Create certificate and key files from Github secrets
      env:
        DIGICERT_TIP_WILDCARD_CERT: ${{ secrets.DIGICERT_TIP_WILDCARD_CERT }}
        DIGICERT_TIP_WILDCARD_KEY: ${{ secrets.DIGICERT_TIP_WILDCARD_KEY }}
      run: |
        cat certificates/issuer.pem certificates/root.pem > docker-compose/ucentral-data/certs/restapi-ca.pem
        echo "$DIGICERT_TIP_WILDCARD_CERT" > docker-compose/ucentral-data/certs/websocket-cert.pem
        echo "$DIGICERT_TIP_WILDCARD_CERT" > docker-compose/ucentral-data/certs/restapi-cert.pem
        echo "$DIGICERT_TIP_WILDCARD_KEY" > docker-compose/ucentral-data/certs/websocket-key.pem
        echo "$DIGICERT_TIP_WILDCARD_KEY" > docker-compose/ucentral-data/certs/restapi-key.pem

    - name: Instantiate Docker Compose deployment
      env:
        UCENTRALGW_TAG: ${{ github.sha }}
      run: |
        docker-compose -f docker-compose/docker-compose.yml --project-directory docker-compose/ up -d

    - name: Wait for uCentralGW to be alive and kicking
      run: |
        n=0
        until [ "$n" -ge 3 ]
        do
          curl -s 127.0.0.1:15015 && break
          n=$((n+1)) 
          if [ "$n" -eq 3]; then        
            exit 1
          else
            sleep 3
          fi
        done

    - name: Check functionality of uCentralGW
      env:
        UCENTRALGW: "ucentral.cicd.lab.wlan.tip.build:16001"
        FLAGS: "-s --cacert docker-compose/ucentral-data/certs/restapi-ca.pem --resolve ucentral.cicd.lab.wlan.tip.build:16001:127.0.0.1"
      run: |
        ./test_scripts/curl/cli listdevices

    - name: Display information about running containers and log ucentralgw output
      if: success() || failure()
      run: |
        docker ps -a
        docker logs ucentral_ucentralgw_1

    # disable until repo is public
    #- name: export Docker image
    #  run: docker image save -o wlan-cloud-ucentralgw-${{ github.sha }}.tar wlan-cloud-ucentralgw:${{ github.sha }}

    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: docker-image
    #    path: wlan-cloud-ucentralgw-${{ github.sha }}.tar
