name: CI

on:
  push:
    paths-ignore:
      - 'openapi/**'
      - '**.md'
    branches:
      - master
      - 'release/*'
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-20.04
    env:
      DOCKER_REGISTRY_URL: tip-tip-wlan-cloud-ucentral.jfrog.io
      DOCKER_REGISTRY_USERNAME: ucentral
    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        install: true

    - name: Log into Docker registry
      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/pull/') || github.ref == 'refs/heads/master'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY_URL }}
        username: ${{ env.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: Set branch name output
      id: set_branch_name
      run: |
        if [[ ${GITHUB_REF} == "refs/heads/"* ]]
        then
          echo ::set-output name=branch_name::$(echo ${GITHUB_REF#refs/heads/} | tr '/' '-')
        else
          if [[ ${GITHUB_REF} == "refs/tags/"* ]]
          then
            echo ::set-output name=branch_name::$(echo ${GITHUB_REF#refs/tags/} | tr '/' '-')
          else # PR build
            echo ::set-output name=branch_name::$(echo ${GITHUB_HEAD_REF#refs/heads/} | tr '/' '-')
          fi
        fi

    - name: Build and push
      if: startsWith(github.ref, 'refs/tags/') || startsWith(github.ref, 'refs/pull/') || github.ref == 'refs/heads/master'
      uses: docker/build-push-action@v2
      env:
        BRANCH_NAME: ${{ steps.set_branch_name.outputs.branch_name }}
      with:
        context: .
        push: false
        tags: ${{ env.DOCKER_REGISTRY_URL }}/owgw:${{ github.sha }},${{ env.DOCKER_REGISTRY_URL }}/owgw:${{ env.BRANCH_NAME }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

#  trigger-testing:
#    if: startsWith(github.ref, 'refs/pull/')
#    runs-on: ubuntu-latest
#    needs: docker
#    steps:
#    - name: Get base branch name and set as output
#      id: get_base_branch
#      run: |
#        echo ::set-output name=branch::$(echo ${GITHUB_BASE_REF##*/} | sed 's/master/main/g')
#
#    - name: Checkout actions repo
#      uses: actions/checkout@v2
#      with:
#        repository: Telecominfraproject/.github
#        path: github
#
#    - name: Trigger testing of OpenWifi Docker Compose deployment and wait for result
#      uses: ./github/composite-actions/trigger-workflow-and-wait
#      env:
#        BASE_BRANCH: ${{ steps.get_base_branch.outputs.branch }}
#      with:
#        owner: Telecominfraproject
#        repo: wlan-testing
#        workflow: ow_docker-compose.yml
#        token: ${{ secrets.WLAN_TESTING_PAT }}
#        ref: master
#        inputs: '{"owgw_version": "${{ github.sha }}", "owgwui_version": "${{ env.BASE_BRANCH }}", "owsec_version": "${{ env.BASE_BRANCH }}", "owfms_version": "${{ env.BASE_BRANCH }}", "owprov_version": "main", "owprovui_version": "main"}'
