name: CI

on:
  push:
    paths-ignore:
      - 'openapi/**'
      - '**.md'
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  docker:
    runs-on: ubuntu-20.04
    env:
      DOCKER_REGISTRY_URL: tip-tip-wlan-cloud-ucentral.jfrog.io
      DOCKER_REGISTRY_USERNAME: ucentral
    steps:
    - uses: actions/checkout@v2

    - name: build Docker image
      run: docker build -t wlan-cloud-ucentralgw:${{ github.sha }} .

    - name: log into Docker registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY_URL }}
        username: ${{ env.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

    - name: push Docker image
      run: |
        TAGS="${{ github.sha }}"

        if [ ${GITHUB_REF} == "refs/heads/master" ]
        then
          TAGS="$TAGS ${GITHUB_REF#refs/heads/}"
        else # PR build
          CURRENT_TAG=$(echo ${GITHUB_HEAD_REF#refs/heads/} | tr '/' '-')
          TAGS="$TAGS $CURRENT_TAG"
        fi

        echo "Pushing tags $TAGS"

        for tag in $TAGS; do
          docker tag wlan-cloud-ucentralgw:${{ github.sha }} ${{ env.DOCKER_REGISTRY_URL }}/ucentralgw:$tag
          docker push ${{ env.DOCKER_REGISTRY_URL }}/ucentralgw:$tag
        done

    # disable until repo is public
    #- name: export Docker image
    #  run: docker image save -o wlan-cloud-ucentralgw-${{ github.sha }}.tar wlan-cloud-ucentralgw:${{ github.sha }}

    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: docker-image
    #    path: wlan-cloud-ucentralgw-${{ github.sha }}.tar
